# NOTE: The base image is `debian:stretch` but we uses basically `debian:buster`.
#       See https://github.com/freebroccolo/docker-haskell/issues/94
#
# NOTE: The version `8.6.5` is not latest and is including Cabal 2.4 (not latest too).
#       Because ShellCheck does not work yet on the both latest versions.
#       See https://github.com/koalaman/shellcheck/blob/de9ab4e6ef5262eeba6871a03ef3938a93b44395/ShellCheck.cabal#L40
FROM haskell:8.8.1

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

# Following instructions should be run by $RUNNER_USER
USER $RUNNER_USER

<%= ERB.new(File.read('base/Dockerfile.build-ruby.erb')).result %>

CMD ghci --version && cabal --version
