<%= ERB.new(File.read('base/Dockerfile.git.erb')).result %>

FROM haskell:9.0.1-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD ghci --version && cabal --version
