# NOTE: The base image is `debian:stretch` but we uses basically `debian:buster`.
#       See https://github.com/haskell/docker-haskell/issues/8
FROM haskell:8.10.1

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD ghci --version && cabal --version
