FROM swift:5.2

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD swift -version
