<%= ERB.new(File.read('base/Dockerfile.git.erb')).result %>

FROM openjdk:14.0.1-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

# Install Maven
ARG MAVEN_VERSION=<%= ENV.fetch('MAVEN_VERSION') %>
ARG MAVEN_BINARY_URL=https://www.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
ARG MAVEN_BINARY_FILE=apache-maven-${MAVEN_VERSION}-bin.tar.gz
ARG MAVEN_HOME=${RUNNER_USER_HOME}/maven
ENV PATH ${MAVEN_HOME}/bin:${PATH}
RUN cd "${RUNNER_USER_HOME}" && \
    curl -fsSLO --compressed "${MAVEN_BINARY_URL}" && \
    curl -fsSL  --compressed "${MAVEN_BINARY_URL}.sha512" | \
      xargs -I {} echo "{} *${MAVEN_BINARY_FILE}" | \
      sha512sum --check --strict && \
    mkdir -p "${MAVEN_HOME}" && \
    tar -xzf "${MAVEN_BINARY_FILE}" -C "${MAVEN_HOME}" --strip-components 1 && \
    rm "${MAVEN_BINARY_FILE}" && \
    mvn -v

<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD ["java", "-version"]
