FROM golang:1.13.8-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

# Install Glide
# See https://github.com/Masterminds/glide
RUN curl https://glide.sh/get | sh

<%= ERB.new(File.read('base/Dockerfile.build-ruby.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD go version
