<%= ERB.new(File.read('base/Dockerfile.git.erb')).result %>

FROM golang:1.16.7-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD ["go", "version"]
