FROM debian:buster-20190708

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

# Following instructions should be run by $RUNNER_USER
USER $RUNNER_USER

<%= ERB.new(File.read('base/Dockerfile.build-ruby.erb')).result %>

# Install pyenv
USER $RUNNER_USER
RUN curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
ARG PYENV_SHIMS_BIN="$RUNNER_USER_HOME/.pyenv/shims"
ARG PYENV_BIN="$RUNNER_USER_HOME/.pyenv/bin"
ENV PATH $PYENV_SHIMS_BIN:$PYENV_BIN:$PATH

# Install python 2 and 3
RUN pyenv install 2.7.16 & \
    pyenv install 3.7.4 & \
    wait && \
    pyenv rehash && \
    pyenv global 3.7.4
CMD pyenv versions
