<%= ERB.new(File.read('base/Dockerfile.git.erb')).result %>

FROM python:3.8.6-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

# Install Pipenv
RUN pip install pipenv

<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD ["python", "--version"]
