<%= ERB.new(File.read('base/Dockerfile.git.erb')).result %>

FROM debian:buster-20210816

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD ["ruby", "--version"]
