FROM debian:buster-20210621 AS git-builder

ARG GIT_VERSION=2.32.0
ARG GIT_SOURCE_TARBALL=git-${GIT_VERSION}.tar.xz
ARG GIT_SOURCE_URL=https://mirrors.edge.kernel.org/pub/software/scm/git/${GIT_SOURCE_TARBALL}
ARG GIT_SOURCE_SHA256_URL=https://mirrors.edge.kernel.org/pub/software/scm/git/sha256sums.asc
ARG DEBIAN_FRONTEND=noninteractive

# See:
# - https://git-scm.com/book/en/v2/Getting-Started-Installing-Git#_installing_from_source
# - https://github.com/git/git/blob/v2.32.0/INSTALL
# - https://github.com/git/git/blob/v2.32.0/Makefile
RUN apt-get update -y && \
    apt-get install -qq -y --no-install-recommends \
      dh-autoreconf \
      libcurl4-gnutls-dev \
      libexpat1-dev \
      libz-dev \
      libssl-dev \
      curl \
      ca-certificates \
      ;
RUN curl -fsSLO --compressed "${GIT_SOURCE_URL}" && \
    curl -fsSL --compressed "${GIT_SOURCE_SHA256_URL}" | \
      grep "${GIT_SOURCE_TARBALL}" | \
      sha256sum --check --strict && \
    tar -xf "${GIT_SOURCE_TARBALL}" && \
    cd "git-${GIT_VERSION}" && \
    make prefix=/opt/git NO_TCLTK=1 NO_GETTEXT=1 install
