COPY base/bin/prepare /tmp/devon_rex_work/
RUN /tmp/devon_rex_work/prepare

# Install Git and verify the specified version of Git is installed
COPY --from=git-builder /opt/git /
RUN test "$(git --version)" = "git version <%= ENV.fetch('GIT_VERSION') %>"

# Install Ruby
COPY --from=ruby:<%= ENV.fetch('GLOBAL_RUBY_VERSION') %> /usr/local /usr/local/

# Change owner to let $RUNNER_USER add certificate files
# WARNING: This must be done after copying ruby:2.7.2
RUN chown "$RUNNER_USER" /usr/local/share/ca-certificates

# Update the system `gem` and `bundler`. `GEM_HOME` is created automatically by the root user, so `chown` is needed.
RUN gem update --system && \
    chown -R "${RUNNER_USER}:${RUNNER_GROUP}" "${GEM_HOME}"

# Change USER and prepare Bundler
COPY Gemfile /tmp/devon_rex_work/
USER $RUNNER_USER
RUN bundler_version=$(grep --word-regexp 'bundler' /tmp/devon_rex_work/Gemfile | grep --only-matching --extended-regexp '[0-9.]+') && \
    # Verify Bundler installation
    actual_bundler_version=$(bundle -v) && \
    test "${actual_bundler_version}" = "Bundler version ${bundler_version}" || (echo "Unexpected Bundler version! ${actual_bundler_version}" ; exit 1) && \
    # NOTE: Install bundler v1 as well as v2 because runner applications need them
    #       in order to parse both versions of Gemfile.lock.
    #       See https://bunndler.io/blog/2019/01/03/announcing-bundler-2.html
    gem install bundler:1.17.3 && \
    gem info bundler && \
    gem environment && \
    ruby -v && \
    gem -v && \
    bundle -v
