<%= ERB.new(File.read('base/Dockerfile.git.erb')).result %>

FROM php:7.4.23-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

USER root

# PHP configuration
RUN mv "${PHP_INI_DIR}/php.ini-production" "${PHP_INI_DIR}/php.ini"
COPY php/sider.ini ${PHP_INI_DIR}/conf.d/sider.ini

# Install Composer - https://getcomposer.org/download/
ARG COMPOSER_VERSION=1.10.22
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer --version="${COMPOSER_VERSION}" && \
    php -r "unlink('composer-setup.php');" && \
    composer --version | grep "Composer version ${COMPOSER_VERSION} "
ENV COMPOSER_HOME ${RUNNER_USER_HOME}/.composer
ENV COMPOSER_VENDOR_BIN ${COMPOSER_HOME}/vendor/bin
ENV PATH ${COMPOSER_VENDOR_BIN}:$PATH

USER $RUNNER_USER
RUN mkdir -p "${COMPOSER_VENDOR_BIN}"

<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD ["php", "--version"]
