<%= ERB.new(File.read('base/Dockerfile.git.erb')).result %>

FROM php:8.0.1-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

USER root

# PHP configuration
RUN mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini
COPY php/sider.ini $PHP_INI_DIR/conf.d/sider.ini

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=<%= ENV.fetch('COMPOSER_VERSION') %>

ENV COMPOSER_HOME $RUNNER_USER_HOME/.composer
ENV COMPOSER_VENDOR_BIN $COMPOSER_HOME/vendor/bin
ENV PATH $COMPOSER_VENDOR_BIN:$PATH

USER $RUNNER_USER
RUN mkdir -p $COMPOSER_VENDOR_BIN

<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD php -v && composer --version
