FROM node:12.18.0-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

USER root

COPY npm/package.json /tmp/
RUN npm_version=$(node -pe 'require("/tmp/package.json").dependencies.npm') && \
    npm install --global "npm@${npm_version}" && \
    rm /tmp/package.json

<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD node -v && npm -v && yarn -v
