<%= ERB.new(File.read('base/Dockerfile.git.erb')).result %>

FROM node:14.17.4-buster

<%= ERB.new(File.read('base/Dockerfile.env.erb')).result %>
<%= ERB.new(File.read('base/Dockerfile.prepare.erb')).result %>

USER root
COPY npm/package.json /tmp/
RUN npm_version=$(node -pe 'require("/tmp/package.json").dependencies.npm') && \
    npm install --global "npm@${npm_version}" && \
    test "$(npm --version)" = "${npm_version}" && \
    rm /tmp/package.json

<%= ERB.new(File.read('base/Dockerfile.cleanup.erb')).result %>

CMD ["node", "--version"]
